import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// asset
import imageAsset from '../assets/image/sheep.jpeg';

console.log('xxxx');
console.log(imageAsset);

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>this is homepage title</h1>
        <p>this homepage main</p>
        <img src={imageAsset.src} alt="homepage" height={300}/>
      </main>
    </div>
  )
}
